# This is a basic workflow to help you get started with Actions

name: Test bash

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs with echo
      - name: Run with echo
        env:
          SECRET: ${{ secrets.TEST }}
        run: |
          echo "$SECRET" >> .env
          cat .env 

      # Run with print
      - name: Run with print
        env:
          SECRET: ${{ secrets.TEST }}
        run: |
          printf $SECRET >> .env
          cat .env 
